### PR TITLE
Redmine 4 Support: Replace alias_method_chain

### LINKED ISSUE #19: Redmine v4.0.0 support
Which version of Redmine does this plugin support?
It already supports Redmine v4.0.0?

### LINKED ISSUE #21: Redmine version 4.0.2 support
My environment is Redmine version 4.0.2.stable. We would like support by all means because we want to do SSO by OpenID Connect.

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ApplicationController:Class
Did you mean?  alias_method
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/lib/redmine_openid_connect/application_controller_patch.rb:7:in `block in included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/lib/redmine_openid_connect/application_controller_patch.rb:6:in `class_eval'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/lib/redmine_openid_connect/application_controller_patch.rb:6:in `included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/init.rb:18:in `include'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_openid_connect/init.rb:18:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by joshocalico**
- Use prepend in controller hooks
- Increase version number to signify update
- Support Redmine 4
- Add version to Migration

Fixes #21 
Fixes #19

### CODE REVIEW

**Comment by Valeran86** [comment]
Hello, @joshocalico. I have exactly the same issue. When I clone your fork, problems with `alias_method_chain` was solved, Redmine started successfuly and I saw plugin & its dialog. But when I set url of SSO server and push `Apply` button, this page/plugin fails with error:
```
Started GET "/redmine/settings/plugin/redmine_openid_connect" for 10.244.3.227 at 2019-05-13 09:53:48 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_openid_connect"}
  Current user: admin (id=1)
  Rendering settings/plugin.html.erb within layouts/admin
  Rendered plugins/redmine_openid_connect/app/views/settings/_redmine_openid_connect_settings.html.erb (1.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (2.5ms)
  Rendered admin/_menu.html.erb (3.2ms)
  Rendering layouts/base.html.erb
  Rendered layouts/base.html.erb (15.0ms)
Completed 500 Internal Server Error in 34ms (ActiveRecord: 9.6ms)

ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "oic_sessions" does not exist
LINE 8:                WHERE a.attrelid = '"oic_sessions"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"oic_sessions"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
    119:
    120: <div id="footer">
    121:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2019 Jean-Philippe Lang
    122: </div>
    123: </div>
    124: </div>
    125: <%= call_hook :view_layouts_base_body_bottom %>

plugins/redmine_openid_connect/lib/redmine_openid_connect/hooks.rb:14:in `view_layouts_base_body_bottom'
```
In addition, logout button seems to be non-working anymore... Any suggestions?

**Comment by joshocalico** [comment]
@Valeran86 Is everything working okay now? I got a mention in my email.

**Comment by Valeran86** [comment]
@joshocalico, yes, everything fine. I had problem with my docker container (I forgot to run ’rake redmine:plugins:migrate’, so it was just my fault)

**Comment by triplem** [comment]
Thanks for providing this PR ;-)

**Comment by SIkebe** [comment]
Congrats!
@triplem Is there any document that lists supported Redmine versions?

**Comment by triplem** [comment]
@SIkebe not yet. feel free to add a new wiki page.

**Comment by joshocalico** [comment]
@triplem I'm just glad I could help out 😄

**Comment by triplem** [comment]
@joshocalico Thanks for helping out here 👍

**Comment by SIkebe** [comment]
@triplem When will be the new version released? Is there any remaining tasks we can help?

**Pull request merged**
